Repository ruby-concurrency/concurrent-ruby, pull requests merged in 2018-07, with the labels that each got.

#734 Fix Array/Hash/Set construction broken on TruffleRuby
  lib/concurrent/array.rb
  lib/concurrent/hash.rb
  lib/concurrent/set.rb
  lib/concurrent/thread_safe/util/data_structures.rb
  spec/concurrent/array_spec.rb
  spec/concurrent/hash_spec.rb
  spec/concurrent/set_spec.rb
Labels: bug, in progress

#708 Prefer platform specific memory barriers
  ext/concurrent/atomic_reference.c
  ext/concurrent/extconf.rb
Labels: enhancement, in progress, soon

#733 Update travis CI adding latest Ruby and JRuby versions; fix failure on JRuby 9.2
  .travis.yml
  lib/concurrent/synchronization/abstract_struct.rb
Labels: bug, chore, in progress

#740 Drop support for CRuby 1.9, JRuby 1.7, Rubinius. Add TruffleRuby
  .travis.yml
  README.md
Labels: in progress

#741 Raise on recursive Delay#value call
  lib/concurrent/delay.rb
  spec/concurrent/delay_spec.rb
Labels: in progress

#744 More debug information on intermittent test failure
  spec/concurrent/synchronization_spec.rb
Labels: in progress

#745 Fix agent spec timing
  spec/concurrent/agent_spec.rb
  spec/concurrent/atomic/cyclic_barrier_spec.rb
  spec/concurrent/map_spec.rb
  spec/concurrent/synchronization_spec.rb
  spec/support/example_group_extensions.rb
Labels: bug, in progress

#751 fix small typo on 'lib/concurrent': one -> on
  lib/concurrent.rb
Labels: chore, in progress
