Repository ruby-concurrency/concurrent-ruby, pull requests merged in 2018-05, with the labels that each got.

#706 Update ruby versions in CI
  .travis.yml
Labels: chore

#707 Ensure memory barriers when setting/getting atomic boolean
  .gitignore
  ext/concurrent/atomic_boolean.c
Labels: in progress

#716 Delete .coveralls.yml
  .coveralls.yml
Labels: in progress

#719 update engine detection
  benchmarks/futures-rubyconf2015/benchmarks/special-complete.rb
  benchmarks/futures-rubyconf2015/benchmarks/special-fulfill.rb
  benchmarks/futures-rubyconf2015/benchmarks/special-new.rb
  benchmarks/futures-rubyconf2015/benchmarks/special-value.rb
  lib/concurrent/array.rb
  lib/concurrent/hash.rb
  lib/concurrent/map.rb
  lib/concurrent/set.rb
  lib/concurrent/synchronization/lockable_object.rb
  lib/concurrent/synchronization/object.rb
  lib/concurrent/synchronization/volatile.rb
  lib/concurrent/utility/engine.rb
  lib/concurrent/utility/processor_counter.rb
Labels: in progress

#722 Fix spelling in doc block
  lib/concurrent/channel/buffer/base.rb
Labels: enhancement, in progress
