Repository ruby-concurrency/concurrent-ruby, pull requests merged in 2019-02, with the labels that each got.

#797 Remove shebang from Rakefile
  Rakefile
Labels: chore

#793 Fixes a code comment in Concurrent::{Hash,Array}
  lib/concurrent/array.rb
  lib/concurrent/hash.rb
Labels: enhancement, in progress

#799 Update truffleruby in CI
  .travis.yml
Labels: in progress
